###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    database:
      image: postgres:11-alpine
      container_name: phpdocker-io-database
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=phpdocker

    api:
      image: nginx:alpine
      container_name: phpdocker-io-api
      working_dir: /application
      volumes:
          - ./backend:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "5000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: phpdocker-io-php-fpm
      working_dir: /application
      volumes:
        - ./backend:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

    frontend:
      image: node:alpine
      container_name: phpdocker-io-frontend
      working_dir: /application
      volumes:
        - ./frontend:/application
      ports:
        - "5001:3000"
      command: yarn start
