parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '11.0'
        charset: utf8
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/App/ORM'
                prefix: 'App\ORM'
                alias: App

        metadata_cache_driver:
            type: pool
            pool: doctrine_system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine_system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine_result_cache_pool
